<?php
define('DB_NAME','local.vpd912.com');
define('DB_USER','root');
define('DB_PASSWORD','');
define('DB_HOST','localhost');
define('DB_CHARSET','utf8');
define('DB_PORT','3308');
define('DB_DRIVER','mysql');
?>